package part1;

import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Ex2_1 class have the next capabilities:
 *      1. Create (n) text files, and print to them random number of lines.
 *      2. Calculate the total number of lines of all the created files one by one.
 *      3. Calculate the total number of lines of all the created files by running concurrently multiple threads.
 *      4. Calculate the total number of lines of all the created files by running tasks concurrently by a thread pool.
 */
public class Ex2_1 {

    /**
     * Create n files with a pre-defined line. the lines number will be randomly generated by the provided bound and seed.
     * @param n - the number of files to create.
     * @param seed - a value to the initialization of the pseudo-random numbers.
     * @param bound - the max number of lines a text file will contain.
     * @return an array of strings holds the names of the created files.
     */
    public static String[] createTextFiles(int n, int seed, int bound) {
        File currentFile = null ;
        FileWriter fileWriter = null ;
        PrintWriter printWriter = null ;
        Random rand = new Random(seed) ;
        int numberOfLines = 0 ;
        String[] fileNames = new String[n] ;
        String currentFileName = "" ;
        String line = "Hello to the OOP world." ;
        for(int i = 0 ; i < n ; i++){
            currentFileName = "file_" + i ;
            currentFile = new File(currentFileName) ;
            try {
                if(currentFile.exists()){
                    currentFile.delete() ;
                }
                currentFile.createNewFile() ;
                fileWriter = new FileWriter(currentFile.getName(), true) ;
                printWriter = new PrintWriter(fileWriter) ;
                numberOfLines = rand.nextInt(bound) ;
                for(int j = 0 ; j < numberOfLines ; j++){
                    printWriter.println(line) ;
                }
                fileNames[i] = currentFileName ;
                printWriter.close();
                fileWriter.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return fileNames ;
    }

    /**
     * Calculates the total number of lines in the files provided one by one.
     * @param fileNames - an array of strings holding a file names to scan.
     * @return the total number of lines.
     */
    public static int getNumOfLines(String[] fileNames){
        long startTime = System.currentTimeMillis() ;
        File currentFile = null ;
        FileReader fileReader = null ;
        BufferedReader bufferedReader = null ;
        int numOfLines = 0 ;
        for (String fileName : fileNames) {
            currentFile = new File(fileName);
            try {
                if (!currentFile.exists()) {
                    throw new FileNotFoundException("The file provided has not been found.");
                } else {
                    fileReader = new FileReader(currentFile);
                    bufferedReader = new BufferedReader(fileReader);
                    while (bufferedReader.readLine() != null) {
                        numOfLines++;
                    }
                    bufferedReader.close();
                    fileReader.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        long endTime = System.currentTimeMillis() ;
        long executionTime = endTime - startTime ;
        System.out.println("The getNumOfLines method runs in: " + executionTime + " Milliseconds.");
        return numOfLines ;
    }

    /**
     * Calculates the total number of lines in the files provided by running a Thread to work on each file.
     * @param fileNames - an array of strings holding a file names to scan.
     * @return the total number of lines.

     */
    public int getNumOfLinesThreads(String[] fileNames){
        long startTime = System.currentTimeMillis() ;
        LinesCounterThread currentThread = null ;
        AtomicInteger atomicInt = new AtomicInteger(0) ;
        AtomicInteger numOfThreadsFinished = new AtomicInteger(0) ;
        int numOfFiles = fileNames.length ;
        for(String fileName: fileNames){
            currentThread = new LinesCounterThread(fileName, atomicInt, numOfThreadsFinished) ;
            currentThread.start();
        }
        while(numOfThreadsFinished.get() != numOfFiles){

        }
        long endTime = System.currentTimeMillis() ;
        long executionTime = endTime - startTime ;
        System.out.println("The getNumOfLinesThreads method runs in: " + executionTime + " Milliseconds.");
        return atomicInt.get() ;
    }
    /**
     * Calculates the total number of lines in the files provided by running a task for each file individually in
     * a thread pool.
     * @param fileNames - an array of strings holding a file names to scan.
     * @return the total number of lines.
     */
    public int getNumOfLinesThreadPool(String[] fileNames){
        long startTime = System.currentTimeMillis() ;
        int totalNumOfLines = 0 ;
        int numOfFiles = fileNames.length ;
        ExecutorService threadPool = Executors.newFixedThreadPool(numOfFiles/10) ;
        List<Future<Integer>> futureList = new ArrayList<>();
        for (String fileName : fileNames) {
            LinesCounterCallable task = new LinesCounterCallable(fileName);
            futureList.add(threadPool.submit(task));
        }
        for(int i = 0 ; i < numOfFiles ; i++){
            try {
                totalNumOfLines += futureList.get(i).get() ;
            } catch (InterruptedException | ExecutionException e) {
                throw new RuntimeException(e);
            }
        }
        threadPool.shutdown();
        long endTime = System.currentTimeMillis() ;
        long executionTime = endTime - startTime ;
        System.out.println("The getNumOfLinesThreadPool method runs in: " + executionTime + " Milliseconds.");
        return totalNumOfLines ;
    }
    
    public static void cleanFiles(){
        String name = "file_" ;
        int i = 0 ;
        boolean keepGoing = true ;
        File file = null ;
        while(keepGoing){
            file = new File(name + i) ;
            if(!file.exists()){
                keepGoing = false ;
            }else{
                file.delete() ;
                i++ ;
            }
        }
    }
}
